rmsREVAMP/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rmsREVAMP.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace rmsREVAMP.Controllers
{
    public class DepartmentController : Controller
    {
        ApplicationDbContext dbcontext = new ApplicationDbContext();
        RoleManagementViewModels rmvm = new RoleManagementViewModels();
        public class DepartmentDesignator
        {
            public string UserId { get; set; }
            public string DepartmentName { get; set; }
        }
        // GET: Department
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetDepartmentsListJson()
        {
            var data = dbcontext.Departments.OrderBy(a => a.Name).ToList();

            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetUsersListJson()
        {
            var data = dbcontext.Users.OrderBy(a => a.Email).ToList();

            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ViewDepartmentOfUser( string id)
        {
            var data = dbcontext.UserDepartments.Where(a => a.UserId == id).Select(n => n.DepartmentCode).ToList();

            foreach (var item in data)
            {
                var departmentName = dbcontext.Departments.Where(b => b.Code == item).Single();
                rmvm.departmentList.Add(departmentName);
            }

            return new JsonResult { Data = rmvm.departmentList, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public ActionResult DeleteDepartment(string id)
        {

            var DelDepartmentById = dbcontext.Departments.Where(n => n.Code == id).ToList().FirstOrDefault();

            if (ModelState.IsValid)
            {
                //dbcontext.UserDepartments.Remove(DelDepartmentById).Where(n => n.DepartmentCode == id);
                dbcontext.Departments.Remove(DelDepartmentById);
                dbcontext.SaveChanges();
            }

            return PartialView("PartialDepartmentList");
        }

        [HttpPost]
        public ActionResult CreateDepartment(Department department)
        {
            IdentityRole generateID = new IdentityRole();

            rmvm.department = department;
            rmvm.department.Code = generateID.Id;

            dbcontext.Departments.Add(rmvm.department);
            dbcontext.SaveChanges();

            ViewBag.ResultMessage = "New department created";

            return PartialView("PartialDepartmentList");
        }

        [HttpPost]
        public ActionResult UpdateDepartment(Department department)
        {
            Department departmentValidate = new Department();

            departmentValidate = dbcontext.Departments.Where(d=>d.Code == department.Code).FirstOrDefault<Department>();
            //departmentValidate.Code = department.Code;

            if (departmentValidate != null)
            {
                departmentValidate.Name = department.Name;
            }
            //departmentValidate.Name = department.Name;

            dbcontext.Entry(departmentValidate).State = System.Data.Entity.EntityState.Modified;
            //dbcontext.Departments.Add(rmvm.department);
            dbcontext.SaveChanges();

            //ViewBag.ResultMessage = "New department created";

            return PartialView("PartialDepartmentList");
        }
    }
}

rmsREVAMP/Controllers/RoleManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rmsREVAMP.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;

namespace rmsREVAMP.Controllers
{
    [Authorize]
    public class RoleManagementController : Controller
    {
        ApplicationDbContext dbcontext = new ApplicationDbContext();
        RoleManagementViewModels rmvm = new RoleManagementViewModels();

        // GET: RoleManagement
        public ActionResult Index()
        {
            //GetRolesList();
            return View();
        }

        //Retrieve All Roles
        public RoleManagementViewModels GetRolesList()
        {
            //Set Rolemanager to Access Extended Identiy Role Class > ApplicationRoles
            var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(dbcontext));


            rmvm.identityRoleList = RoleManager.Roles.ToList();

            return rmvm;
        }

        [HttpPost]
        public ActionResult CreateRole(ApplicationRoles applicationRoles)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbcontext));
            ApplicationUser currentUser = UserManager.FindById(User.Identity.GetUserId());
            
            string Email = currentUser.Email;

            IdentityRole GetSystemGeneratedValue = new IdentityRole();
            
            applicationRoles.Id = GetSystemGeneratedValue.Id;
            applicationRoles.Creator = Email;
            applicationRoles.Modifier = Email;
            applicationRoles.DateCreated = DateTime.UtcNow.ToShortDateString();
            applicationRoles.DateModified = DateTime.UtcNow.ToShortDateString();
            rmvm.applicationRoles = applicationRoles;

            dbcontext.Roles.Add(applicationRoles);
            dbcontext.SaveChanges();

            ViewBag.ResultMessage = "New role created";
            GetRolesList();

            return PartialView("PartialRoleList");
        }

        [HttpPost]
        public ActionResult UpdateRole(ApplicationRoles applicationRoles)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbcontext));
            ApplicationUser currentUser = UserManager.FindById(User.Identity.GetUserId());

            string Email = currentUser.Email;


            IdentityRole roleValidate = dbcontext.Roles.AsNoTracking().Where(d => d.Id == applicationRoles.Id).Single<IdentityRole>();

            if (roleValidate != null)
            {
                applicationRoles.Modifier = Email;
                applicationRoles.DateModified = DateTime.UtcNow.ToShortDateString();

                dbcontext.Entry(applicationRoles).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
            }
            


            return PartialView("PartialRoleDetails");
        }

        public ActionResult DeleteRole(string id)
        {

            var DelRoleById = dbcontext.Roles.Where(n => n.Id == id).ToList().FirstOrDefault();

            if (ModelState.IsValid)
            {
                dbcontext.Roles.Remove(DelRoleById);
                dbcontext.SaveChanges();
            }

            return PartialView("PartialRoleList");
        }

        public JsonResult GetRolesListJson()
        {
            var data = dbcontext.Roles.OrderBy(a => a.Name).ToList();
            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetRoleDetailJson(string id)
        {
            var data = dbcontext
                .Roles
                .Where(a => a.Id == id)
                .Single();

            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        
    }
}

rmsREVAMP/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rmsREVAMP.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;

namespace rmsREVAMP.Controllers
{
    public class UserManagementController : Controller
    {
        ApplicationDbContext dbcontext = new ApplicationDbContext();
        RoleManagementViewModels rmvm = new RoleManagementViewModels();

        public JsonResult GetUsersListJson()
        {
            var data = dbcontext.Users.OrderBy(a => a.Email).ToList();

            return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ViewRolesForUser(string id)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbcontext));

            var RolesInList = UserManager.GetRoles(id).ToList();

            return new JsonResult { Data = RolesInList, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ViewDepartmentsForUser(string id)
        {
            var UserManager = dbcontext.UserDepartments.Where(n => n.UserId == id).Select(d => d.DepartmentCode).ToList();

            foreach(var item in UserManager)
            {
                var getDepartmentName = dbcontext.Departments.Where(n => n.Code == item).Single();
                rmvm.departmentList.Add(getDepartmentName);
            }
            //var RolesInList = UserManager.GetRoles(id).ToList();

            return new JsonResult { Data = rmvm.departmentList, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        // GET: UserManagement
        public ActionResult Index()
        {
            rmvm.identityRoleList = dbcontext.Roles.ToList();
            return View(rmvm);
        }
        public ActionResult ViewUserInformation(string id)
        {
            rmvm.applicationUser = dbcontext.Users.SingleOrDefault(u => u.Id == id);
            rmvm.identityRoleList = dbcontext.Roles.ToList();

            return View(rmvm);
        }
        public ActionResult AddRoleToUser(RoleDesignator applicationUserRole)
        {
            try
            {
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbcontext));
                UserManager.AddToRole(
                        applicationUserRole.UserId,
                        applicationUserRole.RoleName);
                dbcontext.SaveChanges();

                return View("Index");
            }
            catch
            {
                return View("DO NOT ADD");
            }
            
        }
        public ActionResult AddDepartmentToUser(DepartmentDesignator departmentDesignator)
        {

            try {
                var CheckIfExist = dbcontext.UserDepartments
               .Where(n => n.DepartmentCode == departmentDesignator.DepartmentCode)
               .Where(n => n.UserId == departmentDesignator.UserId).Single();

                return View("DO NOT ADD");

            }
            catch
            {
                rmvm.userDepartment.UserId = departmentDesignator.UserId;
                rmvm.userDepartment.DepartmentCode = departmentDesignator.DepartmentCode;
                dbcontext.UserDepartments.Add(rmvm.userDepartment);
                dbcontext.SaveChanges();

                return View("Index");
            }
        }
        public ActionResult DeleteDepartmentToUser(DepartmentDesignator departmentDesignator)
        {

            var deleteDepartment = dbcontext.UserDepartments
                .Where(n => n.DepartmentCode == departmentDesignator.DepartmentCode)
                .Where(n => n.UserId == departmentDesignator.UserId).Single();

            dbcontext.UserDepartments.Remove(deleteDepartment);

            dbcontext.SaveChanges();

            return View("Index");
        }
        public ActionResult DeleteRoleFromUser(RoleDesignator applicationUserRole)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbcontext));
            UserManager.RemoveFromRole(
                    applicationUserRole.UserId,
                    applicationUserRole.RoleName);
            dbcontext.SaveChanges();

            return View("Index");
            //RedirectToAction("Index", controllerName: "ViewUserInformation", routeValues: applicationUserRole);
        }
        //public ActionResult AddRoleRightsToUser()
        //{

        //}
    }

    public class RoleDesignator
    {
        public string UserId { get; set; }
        public string RoleName { get; set; }
    }

    public class DepartmentDesignator
    {
        public string UserId { get; set; }
        public string DepartmentCode { get; set; }
    }
}

rmsREVAMP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Recipe Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.34/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.34/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.34/js/uikit-icons.min.js"></script>
</head>
<body ng-app="AngularApp">
    <nav class="uk-navbar-container " uk-navbar>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
                <li class="uk-active"><a href="#" uk-toggle="target: #offcanvas-push"><span uk-navbar-toggle-icon></span> <span class="uk-margin-small-left">Menu </span></a></li>
            </ul>
        </div>
        <div class="uk-navbar-right uk-margin-right">
            @*<a ><span uk-icon="icon: user"></span> </a>
            <div uk-dropdown="pos: top-left">
                <ul class="uk-nav uk-dropdown-nav uk-text-center">
                    <li></li>
                </ul>
            </div>*@
            @**@
        </div>
    </nav>

    <div id="offcanvas-push" uk-offcanvas="mode: push; overlay: true">
        <div class="uk-offcanvas-bar">
            <button class="uk-offcanvas-close" type="button" uk-close></button>
            <div class="profile-bar uk-padding">
                <div>
                    
                    @if (Request.IsAuthenticated)
                    {
                        @Html.Partial("_LoginPartial")
                    }
                    else
                    {
                        <p>
                            Welcome to the RMS Dashboard, Please
                            @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                             to access the Dashboard.
                        </p>
                    }
                </div>
            </div>
            <ul class="uk-nav-default uk-nav-parent-icon uk-padding-small" uk-nav>
                <li class="uk-active">@Html.ActionLink("Dashboard", "Index", "Home")</li>
                <li class="uk-parent">
                    <a href="#">Management</a>
                    <ul class="uk-nav-sub">
                        <li><a href="#">Materials</a></li>
                        <li>
                            <a href="#">Recipe</a>
                        </li>
                    </ul>
                </li>
                <li class="uk-parent">
                    <a href="#">Administration</a>
                    <ul class="uk-nav-sub">
                        <li>@Html.ActionLink("Roles", "Index", "RoleManagement")</li>
                        <li>@Html.ActionLink("Users", "Index", "UserManagement")</li>
                        <li>@Html.ActionLink("Departments", "Index", "Department")</li>
                    </ul>
                </li>
                <li class="uk-parent">
                    <a href="#">Other</a>
                    <ul class="uk-nav-sub">
                        <li><a href="#">Virtual Laboratory</a></li>
                        <li><a href="#">POS Products</a></li>
                    </ul>
                </li>
                
            </ul>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RMS Dashboard</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularui")
    @RenderSection("scripts", required: false)
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    @*Angular*@
    <script src="~/Scripts/AngularControllers/AngularBootstrap.js"></script>
    <script src="~/Scripts/AngularControllers/RolesManagement.js"></script>
    <script src="~/Scripts/AngularControllers/UsersManagement.js"></script>
    <script src="~/Scripts/AngularControllers/SingleUserManagement.js"></script>
    <script src="~/Scripts/AngularControllers/DepartmentsManagement.js"></script>
</body>
</html>